### ISSUE TITLE
Finding difference between voxels of two different protein

### ISSUE THREAD

**Issue by wdorji** [Acellera/moleculekit#104]
Hello,

I wanted to ask if there is any way to find the difference between the voxels of two proteins and see how much similar they are?

**Comment by stefdoerr** [comment]
Hi. You can implement any metric you want since they are just numerical arrays.
I guess the simplest is just the absolute of the difference. Something like:
```
np.abs(x[:, 0] - y[:, 0])
```
which would get the absolute difference per voxel for channel 0 etc.
