### ISSUE TITLE
viewCrystalPacking writes cell onto top molecule

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/moleculekit#11]
Should instead first visualize the protein packing and then draw on that molecule the cell, or create a new dummy molecule on which to visualize the cell. Otherwise if you call it twice for different molecules it will write the cell lines on the previous molecule.

**Comment by j3mdamas** [comment]
I think https://github.com/Acellera/moleculekit/pull/10 will close this as well, right?

**Comment by stefdoerr** [comment]
yes yes

**Comment by stefdoerr** [comment]
Thanks @j3mdamas !

**Comment by j3mdamas** [comment]
Also, it was the first time I use the beta feature of transfering issues and it worked nicely.
