### ISSUE TITLE
Add sasa option to the atom selection language

### ISSUE THREAD

**Issue by ajasja** [Acellera/moleculekit#110]
It would be really cool if one could select residues by SASA. 

One could then easily select surface hydrophobics 
` (sasa>30 and hydrophobic)`

or just the core of the protein in chain A `(sasa<30 and chain A)`

Also the atom selection language could be coupled to deep learning models as showcased by Simon Duerr's excellent protein MPNN demo: https://twitter.com/simonduerr/status/1544634136714944512 

Things to consider: 
- SASA has a few parameters. Perhaps the user could call `molecule.calculate_SASA(radius, points, etc...)`
- Should the selection be per atom or per residue? For design per residue is more useful. there could be a `sasa_atom` that would be per atom

**Comment by stefdoerr** [comment]
Hi Ajasja, in atom selection language we are trying to replicate VMD so currently we are not planning on implementing additional options. In the future we might consider if we want to extend the atomselect language.

You can however calculate SASA with the [MetricSasa](https://software.acellera.com/docs/stable/moleculekit/moleculekit.projections.metricsasa.html) class. You can also choose if you want per atom or per residue.
