### ISSUE TITLE
Update getFingerprint in moleculekit

### ISSUE THREAD

**Issue by NikSchap2107** [Acellera/moleculekit#111]
Current fingerprint does not take chirality into account. This needs to be updated in the following location:
return AllChem.GetHashedMorganFingerprint(self._mol, radius, num_bits)

to

return AllChem.GetHashedMorganFingerprint(self._mol, radius, num_bits, useChirality=True)

**Comment by stefdoerr** [comment]
https://github.com/Acellera/moleculekit/commit/9a74337659563f6edef2af5c16953fab32d9b98f
Done

**Comment by stefdoerr** [comment]
Oops, undid the accidental change in fixHs https://github.com/Acellera/moleculekit/commit/96d2cb3dc6235288d4dde2b0f92fd4206b7f4549
