### ISSUE TITLE
atomselect fails on resnames that start with number

### ISSUE THREAD

**Issue by duerrsimon** [Acellera/moleculekit#113]
```
import moleculekit
moleculekit.__version__
```
returns 1.2.8

`mol.atomselect('resname 1PE')`
causes this error
RuntimeError: Syntax error at ''PE''

`mol.atomselect('resname "1PE"')` works correctly. 
VMD handles 1PE without problem so in order to be a perfect replicate of VMD this should be fixed.

**Comment by stefdoerr** [comment]
Yes we noticed it as well I just was not sure if VMD worked on those. I need to restructure a tiny bit the grammar but it should be an easy fix I believe. Thanks for making it clear that it's a regression!

**Comment by stefdoerr** [comment]
https://github.com/Acellera/moleculekit/commit/fca7c307191dd8162fb4662108e33c4098225c6b
This commit fixes it. I'll make a new release now

**Comment by stefdoerr** [comment]
Released now
