### ISSUE TITLE
Charges from pdb2pqr

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#136]
Hello,

thank you for creating the moleculekit tool! I am currently using pdb2pqr in my workflow and I would like to replace it with your systemPrepare function, because it takes ligands into account when protonating a protein. My problem is that in my workflow I am also using the charges produced by the pdb2pqr tool, which pdb2pqr stores in a .pqr file by default.  I would like to ask if there is any way to access the charges from pdb2pqr through your moleculekit library? Thank you!

**Comment by stefdoerr** [comment]
```py
{'type': 'ATOM', 'serial': 1, 'name': 'N', 'alt_loc': '', 'res_name': 'ILE', 'chain_id': 'A', 'res_seq': 16, 'ins_code': '', 'x': -8.096, 'y': 9.599, 'z': 20.309, 'occupancy': 1.0, 'temp_factor': 8.95, 'seg_id': '1', 'element': 'N', 'charge': '', 'bonds': [<pdb2pqr.structures.Atom object at 0x7413474cd6c0>, <pdb2pqr.structures.Atom object at 0x741347012ec0>, <pdb2pqr.structures.Atom object at 0x7413470136d0>, <pdb2pqr.structures.Atom object at 0x741347013550>], 'reference': <pdb2pqr.definitions.DefinitionAtom object at 0x7413473b0dc0>, 'residue': <pdb2pqr.aa.ILE object at 0x7413474cd630>, 'radius': 2.0, 'ffcharge': -0.32, 'hdonor': True, 'hacceptor': False, 'cell': (-10, 5, 20), 'added': 0, 'optimizeable': 0, 'refdistance': -1, 'id': None, 'mol2charge': None}
```
you mean like this `ffcharge` property of ATOM here?
If you go here to propmap https://github.com/Acellera/moleculekit/blob/main/moleculekit/tools/preparation.py#L823 you can add one last mapping `("ffcharge", "charge")` to that list and it will include those charges

**Comment by dargen3** [comment]
Thank you for your quick response! Just what I need. I'll try it tomorrow. Should I do a pull request with this change?

**Comment by stefdoerr** [comment]
No thanks, we don't really want those charges from pdb2pqr. We prefer AMBER, gasteiger or RESP charges through building and small molecule parameterization.
