### ISSUE TITLE
Wrong numbering of added hydrogens

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#139]
Hello,

I would like to report a wrong numbering of hydrogens added to the mmCIF file using the systemPrepare function.

Script to reproduce the error (The structure was [downloaded](https://www.rcsb.org/structure/1alf) from the PDB database.):
``` python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare

molecule = molit.Molecule("1alf.cif")
prepared_molecule = systemPrepare(molecule, 7)
prepared_molecule.write("protonated_protein.cif")
```

In the resulting file, the hydrogens in the second column are incorrectly numbered:

ATOM    1  N  N     .  SER  A  1   1  .   15.105  -1.173  -7.265  1.0  0.0  0   1  SER  A  N     1  
ATOM    2  C  CA    .  SER  A  1   1  .   14.093  -2.042  -6.671  1.0  0.0  0   1  SER  A  CA    1  
ATOM    3  C  C     .  SER  A  1   1  .   13.120  -1.246  -5.834  1.0  0.0  0   1  SER  A  C     1  
ATOM    4  O  O     .  SER  A  1   1  .   13.354  -0.084  -5.485  1.0  0.0  0   1  SER  A  O     1  
ATOM    5  C  CB    .  SER  A  1   1  .   14.754  -3.177  -5.850  1.0  0.0  0   1  SER  A  CB    1  
ATOM    6  O  OG    .  SER  A  1   1  .   14.789  -4.424  -6.553  1.0  0.0  0   1  SER  A  OG    1  
ATOM    1  H  H1    .  SER  A  1   1  .   16.021  -1.520  -7.054  1.0  0.0  0   1  SER  A  H1    1  
ATOM    1  H  HA    .  SER  A  1   1  .   13.581  -2.477  -7.422  1.0  0.0  0   1  SER  A  HA    1  
ATOM    1  H  HB2   .  SER  A  1   1  .   15.690  -2.905  -5.631  1.0  0.0  0   1  SER  A  HB2   1  
ATOM    1  H  HB3   .  SER  A  1   1  .   14.234  -3.299  -5.005  1.0  0.0  0   1  SER  A  HB3   1  
ATOM    1  H  H2    .  SER  A  1   1  .   14.989  -1.143  -8.260  1.0  0.0  0   1  SER  A  H2    1  
ATOM    1  H  H3    .  SER  A  1   1  .   15.016  -0.245  -6.899  1.0  0.0  0   1  SER  A  H3    1  
ATOM    1  H  HG    .  SER  A  1   1  .   14.191  -4.366  -7.348  1.0  0.0  0   1  SER  A  HG    1  
ATOM    7  N  N     .  ALA  A  1   2  .   12.009  -1.870  -5.489  1.0  0.0  0   2  ALA  A  N     1  
ATOM    8  C  CA    .  ALA  A  1   2  .   10.971  -1.218  -4.696  1.0  0.0  0   2  ALA  A  CA    1  
ATOM    9  C  C     .  ALA  A  1   2  .    9.999  -2.232  -4.139  1.0  0.0  0   2  ALA  A  C     1  
ATOM   10  O  O     .  ALA  A  1   2  .    8.933  -2.497  -4.704  1.0  0.0  0   2  ALA  A  O     1  
ATOM   11  C  CB    .  ALA  A  1   2  .   10.290  -0.169  -5.591  1.0  0.0  0   2  ALA  A  CB    1  
ATOM    7  H  H     .  ALA  A  1   2  .   11.934  -2.853  -5.824  1.0  0.0  0   2  ALA  A  H     1  
ATOM    7  H  HA    .  ALA  A  1   2  .   11.411  -0.731  -3.930  1.0  0.0  0   2  ALA  A  HA    1

**Comment by stefdoerr** [comment]
Thanks for the report. It's already fixed in the latest version though. You must be on an older one
https://github.com/Acellera/moleculekit/commit/5748343358718dd33295f4b27d8d0c4a880882ad
