### ISSUE TITLE
Deleted atom by systemPrepare function

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#140]
Hello,

I'd like to report a potential bug. The systemPrepare function removes an atom from the structure. The structure used is [3u5s](https://www.rcsb.org/structure/3u5s).

Script to repeat:
```python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare
molecule = molit.Molecule(f "3u5s.cif")
prepared_molecule = systemPrepare(molecule, pH=7, ignore_ns_errors=True)
prepared_molecule.write(f "protonated_protein.cif")
```

In the PDB database file, there are two phosphorus atoms in the FAD ligand. In the protonated_protein.cif file, there is only one phosphorus atom left in the FAD ligand.

**Comment by stefdoerr** [comment]
Hm, that's sneaky! I'll give it a look

**Comment by stefdoerr** [comment]
In the meanwhile you can remove the ligand before the preparation from the molecule and add it back after systemPrepare

**Comment by dargen3** [comment]
This can be quite problematic when the ligand is covalently bound to the protein. I'd rather wait for a fix.

**Comment by stefdoerr** [comment]
Making 1.9.13 release which fixes this. It was caused by a fix in systemPrepare for nucleic acid terminals. Unfortunately the ligand got recognized as such and was losing its P atom. It's fixed now

**Comment by dargen3** [comment]
Thank you for the quick fix! Please, could such patches be checked if there are more in systemPrepare? I would like to use moleculekit in a workflow for hundreds of thousands of proteins, it will take tens of CPU years to compute on a supercomputer. Finding out after the calculation that such errors are happening would be a nightmare.

**Comment by stefdoerr** [comment]
MoleculeKit is open source and free to use. If you find issues, report them and I fix them or anyone else who wants. We don't give any guarantees of quality, no software is bugfree. I can rather guarantee the opposite, that you *will* find more bugs :)
When running such computations it's good to do them with gradually increasing data sizes so you don't have to redo everything from scratch once you find an issue.

**Comment by stefdoerr** [comment]
Version 1.9.14 is out with the fix
