### ISSUE TITLE
Bond in mmCIF block _struct_conn is ignored

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#141]
Hello,

i would like to report a potential bug. The structure used is [2pws](https://www.rcsb.org/structure/2PWS). Although the structure in the _struct_conn block has defined a disulfide bond between the cysteines:

`disulf2 disulf ? ? AND CYS 28 SG ? ? ? 1_555 AND CYS 44 SG ? ? AND CYS 29 AND CYS 45 1_555 ? ? ? ? ? ? ? 2.550 ? ? `

however, the systemPrepare function adds hydrogens to their sulfur atoms.

![image](https://github.com/user-attachments/assets/f8b06b38-80cb-4a17-908c-d697850e5b73)

Code to repeat the error:

```python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare

molecule = molit.Molecule("2pws.cif")
prepared_molecule = systemPrepare(molecule, pH=7, ignore_ns_errors=True)
prepared_molecule.write(f"protonated_protein.cif")
```

**Comment by stefdoerr** [comment]
systemPrepare ignores bonds in the input structure. This includes disulfide bonds. But it's not an issue for building. If you are using HTMD to build the AMBER system it will remove the hydrogens and automatically bond the cysteines together.

**Comment by dargen3** [comment]
Ok, thank you for quick reply!
