### ISSUE TITLE
Meaning of the _molkit_ff parameter in the systemPrepare function

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#142]
Hello,

I have a modified version of moleculekit according to [issue 136](https://github.com/Acellera/moleculekit/issues/136), which also returns charges from pdb2pqr to the user. However, I found that the charges for some atoms returned by moleculekit do not match the charges produced by pdb2pqr. Moreover, the sum of these charges for the whole molecule is often not a integer.
I found that if I set the argument of the function systemPrepare _molkit_FF=False, the charges from the molecules correspond to the charges from pdb2pqr. But there is no information about this parameter in the [documentation](https://software.acellera.com/moleculekit/moleculekit.tools.preparation.html).  So I would like to please ask what function the _molkit_FF argument has and what effect _molkit_FF=False has on the result.

**Comment by stefdoerr** [comment]
This molkit_ff option extends the pdb2pqr database by adding a few non-canonical residues to it.
And you are indeed right, there is something wrong with the charges there. I didn't notice it before since I'm ignoring the charges.
It's weird though that you say it works without the custom FF. Because that would mean you have some non-canonical AA in your structure which should cause an exception.

**Comment by dargen3** [comment]
I did a bit of research on this error on the [2pws](https://www.rcsb.org/structure/2PWS) structure and there is no non-standard residue except for ibuprofen. The charges are different for cysteines forming disulfide bridges.

```python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare

molecule = molit.Molecule("2pws.cif")
with_molkit_ff = systemPrepare(molecule, pH=7, ignore_ns_errors=True)
without_molkit_ff = systemPrepare(molecule, pH=7, ignore_ns_errors=True, _molkit_ff=False)

for chg_with_molkig_ff, chg_without_molkit_ff in zip(with_molkit_ff.charge, without_molkit_ff.charge):
    print(chg_with_molkig_ff,chg_without_molkit_ff, chg_with_molkig_ff == chg_without_molkit_ff)
```

**Comment by stefdoerr** [comment]
This looks like a pdb2pqr bug honestly. I checked and the differences are only in the `CYX` residues and for some reason it's taking the charges from the `CSS` residue instead. I don't think it makes sense for me to investigate further.

The question is rather why you need those charges. They seem kind of meaningless, I looked at them and it assigns CA and H atoms 0 charge. Why don't you just run it through amber.build and get the AMBER charges or if you have non-canonical AAs through GAFF2 and calculate Gasteiger charges.

**Comment by dargen3** [comment]
Okay, let me try to explain. After protonating a protein, I create a substructure for each atom (for example, the 100 closest atoms to that atom, cut in such a way that I break as few bonds as possible and don't cut through functional groups) and then do a quantum mechanical calculation for that substructure. For these QM calculations to be correct, I need to find out for each substructure its formal charge, which is the sum of all the partial/formal atomic charges that are in that substructure. This formal charge must be close to an integer and must correspond to the charge of each functional group (for example, if there are two negatively charged -COO groups in the substructure, the formal charge of the substructure must be -2). 

I have tested that for standard residues the charges from pdb2pqr nicely meet what I need. I don't think the non-standard residues you added to the pdb2pqr database are necessary for me, so I'll run systemPrepare with _molkit_ff=False.

**Comment by stefdoerr** [comment]
okay!
