### ISSUE TITLE
RuntimeError if the chain field has multiple characters

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#143]
Hello, 

if I try to run the function systemPrepare on a large structure [8OI5](https://www.rcsb.org/structure/8OI5) which has a large number of chains, I get the error: 

runtimeError: the chain field should only contain a single character. 

However, in the case of mmCIF files, the chain may have more than one character, so I suppose this is a bug.

``` python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare

molecule = molit.Molecule("8oi5.cif")
prepared_molecule = systemPrepare(molecule, pH=7, ignore_ns_errors=True)
```

**Comment by stefdoerr** [comment]
It won't work. PDB2PQR which does the protonation reads in PDB files and not CIF files and the PDB format only supports single letters in the chain field.

**Comment by stefdoerr** [comment]
So you can probably only protonate 26*2=52 chains together at a time if you  use A-Z a-z as chain names

**Comment by dargen3** [comment]
Ok, thank you for quick reply.
