### ISSUE TITLE
Moleculekit behaves differently for two identical structures in different mmCIF file formats

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#144]
Hello,

I'd like to report a potential bug. If it's not a bug, I'd like to please ask what I'm doing wrong. I'm working with the 9bfl structure. If I prepare the structure using the systemPrepare function and use an mmCIF file directly from the PDB database [9bfl.cif.txt](https://github.com/user-attachments/files/17687672/9bfl.cif.txt), moleculekit expectedly found 1 covalent bond from protein to non-protein molecules and froze the TRP:A:10 residue bound to the non-protein molecule NH2:A:11. But if I use a slightly modified version of the mmCIF file (deleted some hydrogens, only the first NMR model, etc..) [9bfl_changed.cif.txt](https://github.com/user-attachments/files/17687666/9bfl_changed.cif.txt) the molecule no longer finds the covalent bond from protein to non-protein molecule and hydrogens are added to the TRP:A:10 residue.

Script to reproduce:

```python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare

molecule = molit.Molecule(f"9bfl.cif")
prepared_molecule = systemPrepare(molecule, pH=7)
prepared_molecule.write(f"9bfl_prepared.cif")

molecule = molit.Molecule(f"9bfl_changed.cif")
prepared_molecule = systemPrepare(molecule, pH=7)
prepared_molecule.write(f"9bfl_changed_prepared.cif")

```

I uploaded the mmCIF files as txt files because GIT does not allow to upload files with cif extension.

**Comment by stefdoerr** [comment]
![image](https://github.com/user-attachments/assets/06201ee1-a549-4e74-be5c-f60b2810f185)
you are missing the bond to the NH2 in the second structure

If you look at your files the first one has this section
```
loop_
_chem_comp_bond.comp_id 
_chem_comp_bond.atom_id_1 
_chem_comp_bond.atom_id_2 
_chem_comp_bond.value_order 
_chem_comp_bond.pdbx_aromatic_flag 
_chem_comp_bond.pdbx_stereo_config 
_chem_comp_bond.pdbx_ordinal 
```
which defines bonds between different components.
It's missing in your second file.
