### ISSUE TITLE
Problem with vmd parser

### ISSUE THREAD

**Issue by AlirezaShaneh** [Acellera/moleculekit#20]
(My apologies ... I post this in htmd section)

I want to test htmd on the moleculekit tutorial files. When I type "mol.filter('protein')", program complains and return error that the selection ('protein') is not valid. When I change it to 'mol.filter('all') it works. I also get the same error from prepareProtein module which reports "resname DUM" is not a valid selection.

Maybe the libvmdlib requires update?

Thank you,
Alireza

**Comment by stefdoerr** [comment]
Yes this is probably the case. Until I find a way to cross compile C libraries for OSX unfortunately I won't be able to make it work

**Comment by stefdoerr** [comment]
Good news is that in 2 weeks or so I will get my hands on a half-broken Mac so I'll give it a try compiling the libs and running the tests there.

**Comment by AlirezaShaneh** [comment]
Thank you, Stefan. Please let me know once you updated the library as well as your tests.

Best,

**Comment by stefdoerr** [comment]
Hey @AlirezaShaneh , Toni rebuilt the libraries for OSX. Could you test the latest commit of the github repo and see if it works for you?

**Comment by AlirezaShaneh** [comment]
Hey Stefan,

Thanks a lot. I will try it for sure.

Best,

Alireza

**Comment by AlirezaShaneh** [comment]
Hi Stefan,

Great job! It works like a clock on my mac :-) 

Thank you and Toni.

Best,
Alireza

**Comment by stefdoerr** [comment]
Awesome :) glad to hear that
