### ISSUE TITLE
Conda build 3.7 fails

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/moleculekit#24]
Due to competing dependencies. Should figure out how to build it locally first.

**Comment by stefdoerr** [comment]
No numpy > 1.11 for python 3.7 on official anaconda channels. Our dependency on numpy >1.12 and pandas 0.24.2 (which requires higher numpy) causes the failures. We will have to wait for updated numpy on anaconda for 3.7.

**Comment by raimis** [comment]
The `numpy` is already 1.17.4 available: https://anaconda.org/anaconda/numpy/files?version=1.17.4

**Comment by stefdoerr** [comment]
True, thanks. Some other incompatibility seems to exist. I'll give it a look

**Comment by stefdoerr** [comment]
Fixed finally
