### ISSUE TITLE
Problem in getChannels with the old version

### ISSUE THREAD

**Issue by stemylonas** [Acellera/moleculekit#27]
Trying to reproduce results of the DeepSite paper, i found out that the reported channels in the paper are extracted by applying `version=1` argument to the `getChannels` function (something that should more clearly declared somewhere in the code or the documentation). Applying now this function to my test case, the extracted channels were all zeros except from the last, and i found that it is caused by the `mol.atomtype` which is an array of empty values. In the `version=2` branch of `getChannels` there is a specific atom_typing extraction. Maybe it should be added something similar and to the `version=1` branch?

**Comment by stefdoerr** [comment]
Don't use the version=1. It depends on pdbqt atomtypes which you need to obtain with autodock tools. The version=2 should be the one to use.

**Comment by stefdoerr** [comment]
Here is a tutorial on how to use the voxelization https://software.acellera.com/docs/latest/moleculekit/tutorials/voxelization_tutorial.html

**Comment by stemylonas** [comment]
Does this mean that the features presented in the DeepSite paper can't be reproduced by the moleculekit?

**Comment by stefdoerr** [comment]
They can. If you want the exact same behaviour you will need to convert all your PDBs sot pdbqt formats though with autodock tools otherwise you will not have correct channels.
I would suggest not replicating the exact behaviour though and instead use version 2 because we have fixed some bugs.

**Comment by stefdoerr** [comment]
And as far as I remember with our last tests, version 2 worked similarly well.

**Comment by stemylonas** [comment]
Ok thanks
