### ISSUE TITLE
can't import SmallMol

### ISSUE THREAD

**Issue by hawk31** [Acellera/moleculekit#3]
```pdb
In [2]: from moleculekit.smallmol.smallmol import SmallMol
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-26fcfa8998d6> in <module>()
----> 1 from moleculekit.smallmol.smallmol import SmallMol

/shared/jose/moleculekit/moleculekit/smallmol/smallmol.py in <module>()
     29 
     30 _hybridizations_IdxToType = HybridizationType.values
---> 31 _hybridizations_StringToType = {'S': HybridizationType.S,
     32                                 'SP': HybridizationType.SP,
     33                                 'SP2': HybridizationType.SP2,

AttributeError: type object 'HybridizationType' has no attribute 'S'
```

**Comment by giadefa** [comment]
Failing at import is not very tantric. Do we have tests?

**Comment by stefdoerr** [comment]
We have 72% code test coverage. More than any other project we have written. It's just that I decided that I hate rdkit so it's not in the dependencies. You need to install it yourself. Still the error is...weird... 
Are you sure you have rdkit installed Jose?

**Comment by stefdoerr** [comment]
I will try to add a nicer error for the missing import. I wonder how it doesn't error directly on the rdkit import

**Comment by hawk31** [comment]
I do.

The latest htmdmol does not crash with this.

**Comment by cuzzo87** [comment]
Can be the rdkit version?

**Comment by hawk31** [comment]
Actually @cuzzo87 might have a point. I have an old rdkit version in this env.

```
In [3]: rdkit.__version__
Out[3]: '2015.09.1'
```

**Comment by stefdoerr** [comment]
ah ok then the issue is obvious. Update to the acellera one though! not the official rdkit one

**Comment by stefdoerr** [comment]
Ok if you all want I will add rdkit to the deps so that it's version-fixed.

**Comment by hawk31** [comment]
oh it's actually my fault. For some reason after activating the environment conda was still looking at the packages from the base env.

Sneaky conda.

**Comment by hawk31** [comment]
> Ok if you all want I will add rdkit to the deps so that it's version-fixed.

the official one from the rdkit channel works just fine. No need.

**Comment by stefdoerr** [comment]
Nononono! It's bad.

**Comment by stefdoerr** [comment]
Ok you convinced me to version-lock rdkit to moleculekit. Otherwise people will do this thinking they are clever and hit themselves in the face.

**Comment by hawk31** [comment]
For reference, this one works just fine:

```
In [2]: rdkit.__version__                                                                                                                                                                    
Out[2]: '2018.09.2'
```

**Comment by stefdoerr** [comment]
You think it works fine. That's what I'm telling you. The fact that it doesn't error does not mean it's not full of bugs.

**Comment by stefdoerr** [comment]
Bugs which affect the results and don't cause errors.

**Comment by cuzzo87** [comment]
@hawk31 the version of 2018 is going to fail with some code in the util, like `from rdkit.Chem import ChemicalFeatures`

**Comment by stefdoerr** [comment]
Also it will generate really bad coordinates for molecules

**Comment by hawk31** [comment]
So far I'm just cloning `moleculekit` and exporting it to my `PYTHONPATH`.

Is the expected user behaviour to execute `pip install -e .` ?

**Comment by stefdoerr** [comment]
Conda or pip-install it from pypi or anaconda I'd say. Installing from the
repo is not very clean because I had to do a hack for the dependencies

**Comment by hawk31** [comment]
After removing `rdkit` from the environment, `conda install -c acellera moleculekit`  does not retrieve any rdkit dependency, though:

```
(dockbench) [jose@workspace3 ~]$ conda install -c acellera moleculekit
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /shared/jose/conda/envs/dockbench:

The following NEW packages will be INSTALLED:

    moleculekit: 0.1.6-py36h39e3cac_0 acellera

Proceed ([y]/n)? 
```

**Comment by stefdoerr** [comment]
Read above messages please :)

**Comment by cuzzo87** [comment]
yes because it is not a dependency, You should install it like this:

`conda install -c acellera rdkit`

**Comment by hawk31** [comment]
> Ok if you all want I will add rdkit to the deps so that it's version-fixed.

I am confused.



> yes because it is not a dependency, You should install it like this:
> 
> `conda install -c acellera rdkit`

I am more confused.

So do I install the dependency manually, or will it be added to a deps file eventually?

**Comment by stefdoerr** [comment]
Do you want to wait until it's added to the deps? :P
