### ISSUE TITLE
Metals in voxel generation

### ISSUE THREAD

**Issue by Dom1L** [Acellera/moleculekit#30]
Hi Stefan,

I was trying to generate voxels for structures that contain metals, but I'm not able to pass the `prepareProteinForAtomtyping` or the `getChannels` functions.
Basically fails at this check

https://github.com/Acellera/moleculekit/blob/4be4e4f137f975c3d4f9ecac61628deff38e25dc/moleculekit/tools/atomtyper.py#L109

with 

```
RuntimeError: Found non-protein atoms with resnames ['HG' 'ZN'] in the Molecule. Please make sure to only pass protein atoms.
```

Is there another way to make it work? Otherwise the metal channel will always be empty.
An example PDB that contains zinc would be `1atl`

**Comment by stefdoerr** [comment]
Yes, good point. I guess when Alberto tested it there were no metals in the
tests. I'll fix it on Friday.

**Comment by stefdoerr** [comment]
@Dom1L as far as I can tell I fixed it in the latest commit. Give it a look if you can with other proteins as well and visualize the results to be sure the channels are right.

**Comment by stefdoerr** [comment]
@Dom1L confirmed the metals are working.
