### ISSUE TITLE
importing error for voxeldescriptor

### ISSUE THREAD

**Issue by debbydanwang** [Acellera/moleculekit#34]
Hi Stephan,

I was trying to voxelize a structure, while I got the following error when importing getVoxelDescriptors. Any hints for how to fix this? 

>>> from moleculekit.tools.voxeldescriptors import getVoxelDescriptors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wang123/anaconda3/envs/moleculekit/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 23, in <module>
    occupancylib = ctypes.cdll.LoadLibrary(os.path.join(libdir, "occupancy_ext.so"))
  File "/home/wang123/anaconda3/envs/moleculekit/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/wang123/anaconda3/envs/moleculekit/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/wang123/anaconda3/envs/moleculekit/lib/python3.6/site-packages/moleculekit/lib/Linux/occupancy_ext.so: undefined symbol: __exp_finite

Thanks a lot!

Debby

**Comment by stefdoerr** [comment]
Hm that seems weird. What OS are you using?

**Comment by debbydanwang** [comment]
I'm using centOS 6.5.

**Comment by stefdoerr** [comment]
The C code is compiled as a dynamically linked library. Seems like you are missing some basic math library of C on your machine.
Try the following command:
`ldd /home/wang123/anaconda3/envs/moleculekit/lib/python3.6/site-packages/moleculekit/lib/Linux/occupancy_ext.so`
This will show where it finds each library and I assume you will be missing libc.so.6

To install libc on CentOS this command should do it `yum install glibc-devel`

After that try the `ldd` command again to see if it picked up the location of the libc library

**Comment by debbydanwang** [comment]
Hi Stephan,

Sorry for getting back to you late. I tried the ldd command and libc.so.6 was there. I'm attaching the output of the ldd command as follows. Any other suggestions for fixing the problem? Thank you so much...
![image](https://user-images.githubusercontent.com/55935617/66104065-104b7780-e5ea-11e9-9273-6a85baef49e0.png)


Debby


> The C code is compiled as a dynamically linked library. Seems like you are missing some basic math library of C on your machine.
> Try the following command:
> `ldd /home/wang123/anaconda3/envs/moleculekit/lib/python3.6/site-packages/moleculekit/lib/Linux/occupancy_ext.so`
> This will show where it finds each library and I assume you will be missing libc.so.6
> 
> To install libc on CentOS this command should do it `yum install glibc-devel`
> 
> After that try the `ldd` command again to see if it picked up the location of the libc library

**Comment by stefdoerr** [comment]
Hey, can you try again replacing the so file with this one? Tell me if this one works.
[occupancy_ext.so.tar.gz](https://github.com/Acellera/moleculekit/files/3684948/occupancy_ext.so.tar.gz)

**Comment by debbydanwang** [comment]
Still not working... with the same error...

> Hey, can you try again replacing the so file with this one? Tell me if this one works.
> [occupancy_ext.so.tar.gz](https://github.com/Acellera/moleculekit/files/3684948/occupancy_ext.so.tar.gz)

**Comment by stefdoerr** [comment]
This one?
[occupancy_ext.so.tar.gz](https://github.com/Acellera/moleculekit/files/3685287/occupancy_ext.so.tar.gz)

**Comment by debbydanwang** [comment]
Hi Stephan,

Seems the libmvec.so.1 is missing on my machine, and it works after fixing this. Thanks! 

Debby

> This one?
> [occupancy_ext.so.tar.gz](https://github.com/Acellera/moleculekit/files/3685287/occupancy_ext.so.tar.gz)

**Comment by stefdoerr** [comment]
I am perplexed at how it could require a library which is not shown in `ldd` but I'm no C master. Thanks for figuring it out!
