### ISSUE TITLE
Voxelization of PDB 1E2X ends strange error message

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [Acellera/moleculekit#36]
I faced a RuntimeError when I tried to voxelize 1E2X.

```py
# I tried to voxelize based on https://software.acellera.com/docs/latest/moleculekit/tutorials/voxelization_tutorial.html

from moleculekit.molecule import Molecule
from moleculekit.tools.voxeldescriptors import getVoxelDescriptors, viewVoxelFeatures
from moleculekit.tools.atomtyper import prepareProteinForAtomtyping
from moleculekit.smallmol.smallmol import SmallMol
from moleculekit.home import home
import os

prot = Molecule("pdb1e2x.ent.gz")
prot.filter("protein or ions") # remove H2O and SO4
prot = prepareProteinForAtomtyping(prot)

prot_vox, prot_centers, prot_N = getVoxelDescriptors(prot, buffer=1)
# -> it causes an RuntimeError
# RuntimeError: Found atoms with resnames ['GLN'] in the Molecule 
# which can cause issues with the voxelization. 
# Please make sure to only pass protein atoms and metals.
```

**Comment by stefdoerr** [comment]
Ugh, this is a protein preparation / bonding issue. `pdb2pqr` adds terminal atoms to GLN 227 during the protein preparation but the distances are probably a bit off for atom 3514 so the bonds are not guessed correctly for it and it's not considered "protein" anymore.

```python
In [8]: prot = prepareProteinForAtomtyping(prot)

In [11]: prot.atomselect('not protein', indexes=True)                                                                                                                                                              
Out[11]: array([3514], dtype=int32)

In [12]: prot.get('resname', sel='not protein')                                                                                                                                                                    
Out[12]: array(['GLN'], dtype=object)

In [13]: prot.get('resid', sel='not protein')                                                                                                                                                                      
Out[13]: array([227])
````
If that atom is not close to any site of interest I would suggest removing it with `prot.remove('index 3514')` and continuing with the voxelization. A bit of an extreme solution but sometimes you really can't win with such complex protocols and external software.
If it occurs in many other cases feel free to report them and I will check if anything can be done about it.

**Comment by keisuke-yanagisawa** [comment]
I catch the reason. Hmmmmm...
Actually I met the error several times, and thus far I avoided those by downloading atomtyper.py and voxeldescriptors.py and modified `notallowed = ~(protsel | metalsel)` to `notallowed = ~(protsel | metalsel | stdaasel)` (there is an another reason to decide modify atomtyper.py: some protein has PB, BA, and other metals, btw). 

Actually, I utilized preprocessed PDB files, thus I could not guarantee which PDB record raise the error in original state. If you want, I will check it for original PDB files of interest.

**Comment by keisuke-yanagisawa** [comment]
But my second thought is that below code is probably more robust:
```
prot = Molecule("pdb1e2x.ent.gz")
prot.filter("protein or ions") # remove H2O and SO4
prot = prepareProteinForAtomtyping(prot)
prot.filter("protein or ions") # remove isolated atoms

prot_vox, prot_centers, prot_N = getVoxelDescriptors(prot, buffer=1)
```
Is it valid way to avoid the issue for you?

**Comment by stefdoerr** [comment]
Yes but maybe take a look at how many atoms get removed. the filter method
returns the atoms which were removed so check that it doesnt suddenly
delete 200 atoms or something ;)

**Comment by keisuke-yanagisawa** [comment]
Okay I understand! I will monitor the numbers.

**Comment by stefdoerr** [comment]
I will close the issue for now. If you have any further questions feel free to comment here or open a new one
