### ISSUE TITLE
mol.bonds error after prepareProteinForAtomtyping()

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [Acellera/moleculekit#37]
I encounted another issue with PDBID 5DOW. Below is the minimum code:

```py
from moleculekit.molecule import Molecule
from moleculekit.tools.atomtyper import prepareProteinForAtomtyping
from moleculekit.tools.voxeldescriptors import getVoxelDescriptors


mol = Molecule("pdb5dow.ent.gz")
mol.filter("protein or ions and (not resname CL) and (not resname NA)")
prepareProteinForAtomtyping(mol)
getVoxelDescriptors(mol)
```

It resulted in below error at `getChannels() -> getPDBQTAtomTypesAndCharges() -> atomtypingValidityChecks()`.

>  ValueError: The protein has less bonds than (number of atoms - 1). This seems incorrect. You can assign bonds with `mol.bonds = mol._getBonds()`

The version of moleculekit is 0.1.30. Is there any suggestion to avoid it?

**Comment by stefdoerr** [comment]
`prepareProteinForAtomtyping` returns a Molecule object. You need to use that, not the one you gave as input. It doesn't modify it in-place.

```python
mol = Molecule("5dow")
mol.filter("protein or ions and (not resname CL) and (not resname NA)")
pmol = prepareProteinForAtomtyping(mol)
getVoxelDescriptors(pmol)
```
Best,
Stefan

**Comment by keisuke-yanagisawa** [comment]
Oops, I'm sorry for bothering you...

**Comment by keisuke-yanagisawa** [comment]
I've checked it works well. I'm sorry for my mistake again.

**Comment by stefdoerr** [comment]
No problem at all :)
