### ISSUE TITLE
Pydantic Models

### ISSUE THREAD

**Issue by dgasmith** [Acellera/moleculekit#40]
Hi, really cool package! I was poking through your code (especially the Molecule objects) and noticed that you may be interested in the [Pydantic](https://pydantic-docs.helpmanual.io) package for automatic validation of shapes, class variables, schema, etc. See [here](https://github.com/MolSSI/QCElemental/blob/master/qcelemental/models/molecule.py#L77) for a similar Molecule model implementation with automatic shaping and validation of NumPy arrays and other objects.

This is part of the MolSSI QCArchive [infrastructure](http://docs.qcarchive.molssi.org/en/latest/) tool stack. It may be worth a chat to see if we could collaborate on some core infrastructure!

**Comment by stefdoerr** [comment]
I see. It's a bit similar to our [protocolinterface](https://github.com/Acellera/protocolinterface) (sorry for no documentation) which does type validation of arguments to classes. Back when we wrote the initial version (before the github repo) I had checked and there were no good alternatives but it seems like Pydantic could do it now :) 
A bit too much effort at this point to replace ours which works for what we need though but nice stuff!

I will take a look around QCArchive slack maybe and see what is currently being done.

**Comment by stefdoerr** [comment]
Oh oops, the repo is private. Well, you can see it here more or less how it's used https://github.com/Acellera/htmd/blob/master/htmd/protocols/equilibration_v2.py#L66 not that it's anything sophisticated. Also IDEs hate it which seems to not be the case for Pydantic
