### ISSUE TITLE
Chloride converted to carbon

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/moleculekit#44]
I have encountered this issue in the moleculekit package. 
1) Writing a pdb
In pdb file when there is a CL the name field is expected to be like the following:
```
ATOM      7  C7  ZYI A   1      14.452   7.328  -0.008  1.00 30.28      2    C
ATOM      8 CL8  ZYI A   1      15.987   8.160  -0.102  1.00 36.23      2   CL
ATOM      9  C9  ZYI A   1      14.023   6.546  -1.093  1.00 29.82      2    C
```
But Molecule object wrongly aligned the name field like the following:

```
ATOM      7  C7  ZYI A   1      14.452   7.328  -0.008  1.00 30.28      2    C
ATOM      8  CL8 ZYI A   1      15.987   8.160  -0.102  1.00 36.23      2   CL
ATOM      9  C9  ZYI A   1      14.023   6.546  -1.093  1.00 29.82      2    C
```

This will cause problem to third-party tools that we are using.

2) Using proteinPrepare.
The proteinPrepare convert the CL into C. I think the reason is the same as above, but in this case even if I am able to add a space for the correct alignment I suspect it stripped the string at some point. 
I said that because if:
```
'CL8' --> converted to C
'CL8 ' --> converted to C
'CL81' --> not convert C
[3pdcHTMD.txt](https://github.com/Acellera/moleculekit/files/4147728/3pdcHTMD.txt)
[3pdcORIGINAL.txt](https://github.com/Acellera/moleculekit/files/4147729/3pdcORIGINAL.txt)


```

**Comment by stefdoerr** [comment]
Yes, I can reproduce with 3pdc. I will investigate it later but yes it's a serious issue

**Comment by stefdoerr** [comment]
Fixed! Had to make bugfixes in pdb2pqr code to stop it from using random elements. 0.2.6 moleculekit includes the fix
