### ISSUE TITLE
Issue with vmd viewer

### ISSUE THREAD

**Issue by pkiruba** [Acellera/moleculekit#47]
Hi Dev,

I tried to view a voxel using the below function but nothing is showing up at the end. 

slig = SmallMol("lig.mol2")
lig_vox, lig_centers, lig_N = getVoxelDescriptors(slig, voxelsize=0.5, buffer=1) # gives me 2d output
slig.view(guessBonds=False)
viewVoxelFeatures(lig_vox, lig_centers, lig_N)

I tried to solve it by checking the thread but I am not getting a clear solution for my problem. Last, I am using Mac and I have VMD installed in my applications. I am running code in Jupyter notebook

Thanks.

**Comment by stefdoerr** [comment]
Hi, I answered you in the mojo ticket so I will close this issue.
