### ISSUE TITLE
Issues with prepareProteinForAtomtyping

### ISSUE THREAD

**Issue by zrt** [Acellera/moleculekit#50]
When the mol.chain is all empty, the L83 in moleculekit/moleculekit/tools/preparation.py, set the mol.chain as sequenceID(mol.segid), But L94 use len() function on it, then, TypeError: object of type 'numpy.int64' has no len().

https://github.com/Acellera/moleculekit/blob/ea58f7d30c52cfce7ca26ed6c3d6ba6d669968fc/moleculekit/tools/preparation.py#L83

https://github.com/Acellera/moleculekit/blob/ea58f7d30c52cfce7ca26ed6c3d6ba6d669968fc/moleculekit/tools/preparation.py#L94

**Comment by stefdoerr** [comment]
https://github.com/Acellera/moleculekit/blob/master/moleculekit/tools/preparation.py#L85
I have fixed this issue. You linked to an older commit.
Have you tried updating your moleculekit installation?
