### ISSUE TITLE
problem with prepareProtein

### ISSUE THREAD

**Issue by drewaight** [Acellera/moleculekit#53]
Hello, fantastic work with moleculekit and HTMD, just fantastic. 

I have a problem getting prepareProtein to run or prepareProteinForAtomtyping (im trying to do the voxelization tutorial) and I've reached the limit of my ability to debug the problem. I'm using the conda install of python 3.6 moleculekit 0.3.2, with a moleculekit conda environment and the extra requirements  (pandas 0.22.0 numpy 1.18.5), prepareProtein errors with 
`ValueError: The 'dtype' option is not supported with the 'python-fwf' engine`

on my base conda python 3.7.6 with pandas 1.0.3 numpy 1.18.1 the prepareProtein seems to be throwing an exception in the preparationdata.py module line 123 (def _findRes) at `pos = int(np.argwhere(mask))` with 

`Exception: Data must be 1-dimensional`

[python3.6.txt](https://github.com/Acellera/moleculekit/files/4870376/python3.6.txt)
[python3.7.txt](https://github.com/Acellera/moleculekit/files/4870378/python3.7.txt)

Any insights you have to solving this problem would be greatly appreciated. 

            Drew

**Comment by stefdoerr** [comment]
Thanks a lot! 
Could you give a try with pandas 0.25.3? the 3.6 you posted is with pandas 0.19.2 whichi is too old.
I am not entirely sure why it just now started installing 1.0.3. I need to version lock it or update the code for pandas v1. They really like breaking compatibility between versions, sorry for that.

**Comment by drewaight** [comment]
Success! Thanks so much!

**Comment by stefdoerr** [comment]
Ok HTMD 1.22.5 will now hopefully limit rdkit to 0.25.3 version. Thanks for the report!
