### ISSUE TITLE
Error Smallmol reading file in jupyter-notebook

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/moleculekit#57]
Hi guys,

I started to use HTMD again, and I was doing some simple tests. I was trying to load a mol2 file with SmallMol in a jupyter-notebook session, but apparently there is something going wrong (see the image). If I use an ipython session evrything goes well.

![jupNotebook_smallmol](https://user-images.githubusercontent.com/10772443/98106114-3dc3be00-1e99-11eb-92aa-1733ad4b6e7f.png)

**Comment by stefdoerr** [comment]
You have a broken conda env. Probably same issue as the view issue you opened. 
Did you follow the official installation instructions? I am willing to bet you didn't add the `-c conda-forge` part :)

**Comment by cuzzo87** [comment]
Hi Stefan,

First, thank you for your quick reply and suggestion. I did as the instruction says, but just to try again, I did a fresh installation creating another conda environment. The issue is the same:
```
# packages in environment at /home/alberto/Software/miniconda3/envs/htmd_test:
htmd                      1.23.5                   py36_0    acellera
htmd-deps                 1.23.5                   py36_0    acellera
htmd-pdb2pqr              2.1.1+htmd.14              py_0    acellera
plumed2                   2.3.3+htmd.4                  4    acellera
moleculekit               0.4.3                    py36_0    acellera

```
Can I do any other test for helping you to understand what could be happeing?

**Comment by stefdoerr** [comment]
Can you share with me the mol2 file? I doubt it's a matter of the file since this is an error in internal python stuff but I can at least verify it works for me.

**Comment by cuzzo87** [comment]
Yes, 

It is a mol2 file. 
[lig.txt](https://github.com/Acellera/moleculekit/files/5488148/lig.txt)

I don't know if helps you, but also the #59  persist in the error

**Comment by stefdoerr** [comment]
Just to be sure, you are not running by any chance on MacOSX?

I tested with the file and it reads fine.
Could you try doing:

conda deactivate
unset PYTHONPATH
conda activate htmd
ipython

And running the commands to make sure you don't have some local repo affecting the code?

**Comment by cuzzo87** [comment]
No MacOSX, luckily :). I am on centos, here my release

```
 lsb_release 
LSB Version:	:core-4.1-amd64:core-4.1-noarch

uname -a
Linux 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
My PYTHONPATH is empty. Anyway I tried and error perisist.

**Comment by stefdoerr** [comment]
Can you try to run the commands in ipython instead of notebook?

**Comment by stefdoerr** [comment]
This was resolved I think. If I'm wrong feel free to open again Alberto
