### ISSUE TITLE
Error with getVoxelDescriptors

### ISSUE THREAD

**Issue by kamilla0503** [Acellera/moleculekit#60]
Hi guys,

I am experiencing  problems using function  `getVoxelDescriptors()`

`~/anaconda3/lib/python3.7/site-packages/moleculekit/tools/atomtyper.py in getProperties(mol)
     78         from openbabel import pybel
     79     except ImportError:
---> 80         raise ImportError('Could not import openbabel. The atomtyper requires this dependency so please install it with `conda install openbabel -c conda-forge`')
     81 
     82     name = NamedTemporaryFile(suffix='.pdb').name

ImportError: Could not import openbabel. The atomtyper requires this dependency so please install it with `conda install openbabel -c conda-forge` `

I have installed openbabel. And I do not have any problems with importing:
`import openbabel
from openbabel import *
from pybel import *
import pybel`

How can I fix this problem?

**Comment by stefdoerr** [comment]
are you sure both are installed in the same conda environment?

Start a python console and do:
```
from moleculekit.molecule import Molecule
from openbabel import pybel
```

**Comment by kamilla0503** [comment]
Yes. I have tried and no problems with importing.
Btw, I have updated moleculekit and now I have a new issue with `prepareProteinForAtomtyping(prot)`. 

fn = "3CLV.pdb"
prot = Molecule(fn)
prot = prepareProteinForAtomtyping(prot)
prot.filter("protein or ions") # remove isolated atoms

I partly have output: 
`---- Molecule chain report ----
Chain A:
    First residue: GLY:1:
    Final residue: ILE:207:
---- End of chain report ---`

and error:
`~/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py in resource_filename(self, package_or_requirement, resource_name)
   1127 
   1128     def __init__(self):
-> 1129         self.cached_files = {}
   1130 
   1131     def resource_exists(self, package_or_requirement, resource_name):

~/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py in get_resource_filename(self, manager, resource_name)
   1727         )
   1728 
-> 1729     def _parts(self, zip_path):
   1730         # Convert a zipfile subpath into an egg-relative path part list.
   1731         # pseudo-fs path

NotImplementedError: resource_filename() only supported for .egg, not .zip`


Before updates, I did not have this problems :(

**Comment by stefdoerr** [comment]
This looks pretty bad. The crash is not in our code. I think the conda
environment just broke.
I would suggest either trying to create a new environment or reinstall
miniconda/anaconda.
Updating nearly never works in conda so avoid it.

**Comment by kamilla0503** [comment]
Thank you!

I fixed these problems after reinstallation anaconda and updates packages.

**Comment by stefdoerr** [comment]
Great!
Just because I saw in the previous logs that you were working in the base
environment, I would suggest making a separate environment for HTMD /
Moleculekit. Some stuff from the base environment gets inherited in the
other environments so it can cause issues. Usually I leave base empty and
just create one environment per project.
