### ISSUE TITLE
Error on loading moleculekit (tmalign.dll?)

### ISSUE THREAD

**Issue by NAEV95** [Acellera/moleculekit#61]
OSError                                   Traceback (most recent call last)
<ipython-input-4-f82f33381ea5> in <module>
----> 1 from moleculekit.molecule import Molecule

C:\Anaconda3\envs\moleculekit\lib\site-packages\moleculekit\molecule.py in <module>
      5 #
      6 import numpy as np
----> 7 from moleculekit.util import tempname, ensurelist
      8 from copy import deepcopy
      9 from os import path

C:\Anaconda3\envs\moleculekit\lib\site-packages\moleculekit\util.py in <module>
     15 libdir = home(libDir=True)
     16 if platform.system() == "Windows":
---> 17     tmalignlib = ct.cdll.LoadLibrary(os.path.join(libdir, "tmalign.dll"))
     18 else:
     19     tmalignlib = ct.cdll.LoadLibrary(os.path.join(libdir, "tmalign.so"))

C:\Anaconda3\envs\moleculekit\lib\ctypes\__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

C:\Anaconda3\envs\moleculekit\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: [WinError 126] The specified module could not be found

**Comment by stefdoerr** [comment]
MoleculeKit does not support Windows, sorry. Only Linux is officially supported and OSX might work but we cannot help support it.
