### ISSUE TITLE
smallmol containing Hs

### ISSUE THREAD

**Issue by z-linlinlin** [Acellera/moleculekit#63]
Use SmallMol to transform a molecule with 30 heavy atoms, in version **0.1.12**, it retrurns: SmallMol with **30 atoms** and 1 conformers
But when I updated the moleculekit version to **0.4.7** , it becomes : SmallMol with **52 atoms** and 1 conformers

**Comment by z-linlinlin** [comment]
And I tried SmallMol(mol, fixHs=False, removeHs=True), it didn't work

**Comment by stefdoerr** [comment]
Hi, did you use `force_reading` by any chance?
Can you provide me with the molecule to test?

If it's a mol2 file you can also try directly with rdkit to see if it does the same:
```
from rdkit import Chem
mol = Chem.MolFromMol2File("mylig.mol2", removeHs=False)
mol.GetNumAtoms()
```

**Comment by z-linlinlin** [comment]
Here is simple example:
import moleculekit.smallmol.smallmol as mk
import moleculekit.tools.voxeldescriptors as mk_voxel
from rdkit import Chem
from rdkit.Chem import AllChem
smiles = "CN"
mol = Chem.MolFromSmiles(smiles)
mol_H = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol_H)
mol_conformer = Chem.RemoveHs(mol_H)
smallmol = mk.SmallMol(mol_conformer, fixHs=False)
coords_mol = smallmol.get("coords")[:, :, 0]
channel_mol = mk_voxel.getChannels(smallmol)[0]
print(coords_mol.shape, channel_mol.shape)

**Comment by stefdoerr** [comment]
Oh nice! You found a bug in copying of molecule. I'm fixing it now and will report once it's release in a new moleculekit version (in an hour or so hopefully).
Thanks a lot!

**Comment by stefdoerr** [comment]
Ok version 0.5.5 of moleculekit is out which should fix this. Give it a try and tell me if it worked for you

**Comment by z-linlinlin** [comment]
> Ok version 0.5.5 of moleculekit is out which should fix this. Give it a try and tell me if it worked for you

It works well !
Thanks
