### ISSUE TITLE
Error in atom typing

### ISSUE THREAD

**Issue by shikhar2333** [Acellera/moleculekit#65]
```
prot = Molecule('3PTB', name='Trypsin')
slig = SmallMol('./benzamidine.mol2')
prot = prepareProteinForAtomtyping(prot)
```
The following code snippet gives a runtine error.
The runtime error is:
"Found atoms with resnames ['BEN'] in the Molecule which can cause issues with the voxelization. Please make sure to only pass protein atoms and metals".
Any inputs on how to resolve this?

**Comment by stefdoerr** [comment]
`prot.filter("protein")` before calling prepare

**Comment by shikhar2333** [comment]
Yeah, this removes the RuntimeError.
Thanks.
