### ISSUE TITLE
viewVoxelFeatures uses hardcoded set of features

### ISSUE THREAD

**Issue by cisert** [Acellera/moleculekit#66]
Hi everyone, 

Firstly, thanks for providing this super helpful package! 
I noticed that `moleculekit.tools.voxeldescriptors.viewVoxelFeatures` uses a hardcoded set of eight features for the graphical representation, making it impossible to use the function to draw custom features. Providing a set of eight custom features still works, but will use an incorrect naming scheme. It would be great if this were more customizable. 

Best, 
Clemens

**Comment by cisert** [comment]
Corresponding PR: https://github.com/Acellera/moleculekit/pull/67

**Comment by stefdoerr** [comment]
Hey Clemens, thanks for the PR.
We can only accept PRs though if you sign an agreement found on this page https://software.acellera.com/docs/latest/htmd/developers/howto.html#contributor-agreement
Alternatively if you don't want to sign an agreement I can also add them myself, as you like.

**Comment by cisert** [comment]
Dear Stefan, 
Please feel free to add my suggested changes yourself. 
Thanks for your help and best regards, 
Clemens

**Comment by stefdoerr** [comment]
Thanks again! Added in this commit https://github.com/Acellera/moleculekit/commit/d1a6752428fba75e14deb9a00a8d006683563c9b

**Comment by stefdoerr** [comment]
Sorry for removing the underscore. I agree it's correct python style, it's just that moleculekit is a naming convention mess so I just followed the rest of the file's style. At some point I need to standardize all variable names.

**Comment by cisert** [comment]
Makes perfect sense, I didn't pay attention to the naming convention, sorry about that. One could also add `featurenames` to the docstring. :)
