### ISSUE TITLE
Molecule from SDF file cannot be constructed if there are >100 atoms/bond

### ISSUE THREAD

**Issue by cisert** [Acellera/moleculekit#68]
Dear all, 

I noticed that constructing a Molecule object from an SDF file throws an error if there are more than 100 atoms/bonds in the file, since the counts line does not include a space between the `atom_number` and `bond_number` in this case (https://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf, p. 10). Currently, the number of atoms and bonds in the molecule is determined using 
```
n_atoms, n_bonds = lines[mol_start+3].split()[:2]
```
(https://github.com/Acellera/moleculekit/blob/master/moleculekit/readers.py#L2151) which doesn't work it there's no space between n_atoms and n_bonds. E.g. for a counts line like 
```
110115  0  0  0  0  0  0  0  0999 V2000\n
```
we get `n_atoms = 110115, n_bonds = 0`. See attached [CHEMBL2315234_example.txt](https://github.com/Acellera/moleculekit/files/6013243/CHEMBL2315234_example.txt), which I couldn't upload as an SDF, so I changed the extension to something GitHub supports. 

According to the documentation above, the first three characters of the counts line correspond to `n_atoms`, and characters 4-6 to `n_bonds`, so 
```
n_atoms = lines[mol_start+3][:3]
n_bonds = lines[mol_start+3][3:6]
```
works (`n_atoms` and `n_bonds` are `str` in the current implementation too). I checked this with one-, two-, and three-digit atom and bond numbers and it works fine. 

Since I don't have a signed contributor license, feel free to include this if deemed beneficial. 

Best, 
Clemens

**Comment by stefdoerr** [comment]
Oh yes! Great catch. Actually if you see my SDFWriter I do write it the correct way into the file. I think I just implemented the writer much after the reader and at that point I discovered the right format and then forgot to update the reader. Thanks a lot!

**Comment by stefdoerr** [comment]
Fixed in this commit
https://github.com/Acellera/moleculekit/commit/d1a6752428fba75e14deb9a00a8d006683563c9b
