### ISSUE TITLE
How to cite moleculekit?

### ISSUE THREAD

**Issue by mgarort** [Acellera/moleculekit#70]
What is the appropriate way to cite moleculekit? I haven't been able to find that information on the website or on the GitHub page (sorry if the info is there but I haven't seen it).

Thanks in advance.

**Comment by giadefa** [comment]
Stefan Doerr, Matthew J. Harvey, Frank Noé, and Gianni De Fabritiis. HTMD: High-throughput molecular dynamics for molecular discovery. Journal of Chemical Theory and Computation, 2016, 12 (4), pp 1845–1852.

Thanks!

**Comment by mgarort** [comment]
Great, thanks for the super quick reply! :)
