### ISSUE TITLE
Warning when `atomselect`-ing from molecules with >=100 atoms

### ISSUE THREAD

**Issue by cisert** [Acellera/moleculekit#76]
I can successfully read in molecules with >=100 atoms from SDFs, but when using ```mol.atomselect(...)```, I get a warning along the lines of ```Warning: bond index out of range: 180 60181-0```. The returned result seems to be correct though.  

I suspect this might be related to the lack of a whitespace between the atom-IDs in the bond lines of the SDF when the IDs have three digits. 

Code example: (do ```mv large_mol.txt large_mol.sdf``` before, since Github doesn't support SDF upload)
```
from moleculekit.molecule import Molecule
mol = Molecule("large_mol.sdf")
mol.atomselect("name H")
>> Warning: bond index out of range: 98 20099-0
>> Warning: bond index out of range: 99 20100-0
...
```

System: 
- moleculekit 0.7.8, installed via conda
- Python 3.7.9
- Ubuntu 20.04.2 LTS

[large_mol.txt](https://github.com/Acellera/moleculekit/files/6670299/large_mol.txt)

**Comment by stefdoerr** [comment]
Hi, you need spaces in the bond definitions. 
```
 18 97  1  0
 19 98  1  0
 19 99  1  0
 20100  1  0 # Once you get to triple digits there is no space anymore in your SDF and it messes up the bond reading
 20101  1  0
 21102  1  0
 21103  1  0
````

**Comment by cisert** [comment]
Hi Stefan, thanks for the quick reply. I assumed this could be addressed in the same was this was addressed here: https://github.com/Acellera/moleculekit/issues/68
The file format does not define a whitespace between the atom IDs, see here (https://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf, p. 12).

**Comment by stefdoerr** [comment]
You are right. It seems like I'm not following specs in the bond part. I'll fix it.

**Comment by stefdoerr** [comment]
Ok I fixed it now on master. Can you give it a try? Or do you need a new release? I would like to test it a bit further before releasing although it seems to work on your molecule fine.

**Comment by cisert** [comment]
Great, thanks! Worked for me as well. A new release would be useful for me, if it isn't too much trouble. :)

**Comment by stefdoerr** [comment]
ok moleculekit 0.7.9 is out for python 3.6 and 3.7.
