### ISSUE TITLE
What are the VoxelDescriptors?

### ISSUE THREAD

**Issue by nnguyen19** [Acellera/moleculekit#77]
Hi,
I'm trying to find the descriptions of VoxelDescriptors on your website, but I couldn't find them. What are the atom properties at each channel? Can you elaborate?

I use getVoxelDescriptors from here https://software.acellera.com/docs/latest/moleculekit/moleculekit.tools.voxeldescriptors.html#moleculekit.tools.voxeldescriptors.viewVoxelFeatures

**Comment by giadefa** [comment]
if I understand the question it's written in the same link that you have
sent.
"If no channels are given, the default (‘hydrophobic’, ‘aromatic’,
‘hbond_acceptor’, ‘hbond_donor’, ‘positive_ionizable’,
‘negative_ionizable’, ‘metal’, ‘occupancies’) channels will be used."
