### ISSUE TITLE
OpenBabel warning

### ISSUE THREAD

**Issue by nnguyen19** [Acellera/moleculekit#78]
Whenever I run getVoxelDescriptors I got OpenBabel warning. I tried to install the older version of OpenBabel but it's deprecated, so I stick with the newest one.

![Capture](https://user-images.githubusercontent.com/48696048/132416305-8fa325dd-5d5e-4f7f-9955-37d04a8af9ca.PNG)

**Comment by stefdoerr** [comment]
The warning still exists but we don't care much about kekulization of proteins as long as they are marked as aromatic.
