### ISSUE TITLE
Avoid multiple, redundant queries to PDB

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/moleculekit#88]
Molecule('3PTB') should download once, write to a pdb in working directory and check if f'{pdb_code}.pdb' exists before querying again.

**Comment by stefdoerr** [comment]
I don't think it's a good idea. It's shady behaviour since the user is not
notified and it will fill up random directories full of files and leave it
up to the user to clean them up. The user can just specify to save the file
if they want to use it multiple times with mol.write

**Comment by alejandrovr** [comment]
what about a Molecule('3PTB', cache=True) or specify it in a config file, like the number of cpus?

**Comment by stefdoerr** [comment]
I'm not a fan. I don't see the point since you can save the file as I said. This is only an issue if you write some script processing hundreds of PDB codes at which point you should just save them manually.

**Comment by alejandrovr** [comment]
ok, i see your point... closing!
