### ISSUE TITLE
conda installation fails with PackageNotFoundError

### ISSUE THREAD

**Issue by cisert** [Acellera/moleculekit#91]
Dear all, 

When trying to install moleculekit in a new conda environment (only containing Python 3.7) using `conda install moleculekit -c acellera` as per the README, I always end up with a PackageNotFoundError (see below). Pip installation works fine. 
I'm using macOS 10.15.7 and Miniconda 4.9.2.

Thanks for any help in advance!

![moleculekit_error](https://user-images.githubusercontent.com/38595078/150974033-444cba3c-ebf6-4048-a253-c2ceb56b698c.png)

**Comment by stefdoerr** [comment]
Hi, we don't support OSX. You can proceed at your own risk installing it with pypi
`pip install moleculekit`
Best,
Steafn
